### PR TITLE
CSS MAGIC.

### PR DESCRIPTION
**Pull request by duckinator**
I probably shouldn't be proud of this.

But I am.

Before:
screenshot - 12212015 - 03 27 39 am

After:
screenshot - 12212015 - 03 26 27 am

The animation is also now done using CSS*, instead of JavaScript.

_*adds "HTML+CSS butts and poop" to resume, alongside "HTML+CSS duck"*_

<br><br><br><br><br><br><br><br><br><br><br><br>
* And a JavaScript polyfill.

### CODE REVIEW

**Comment by duckinator** [comment]
I REVERTED THE POOP.

**Comment by negatendo** [comment]
THANK YOU FOR IMPROVING OUR BUTT SYSTEMS DUCKINATOR!

**Comment by duckinator** [comment]
YOU'RE QUITE WELCOME. I IMPROVED THE EFFICIENCY OF YOUR INTER-BUTT TRANSFERS CONSIDERABLY; THEY WERE BLOCKING UP THE ENTIRE SYSTEM BEFORE.

**Comment by negatendo** [comment]
YES WE ALSO APPRECIATE HOW THE BUTTS ARE NOW BIGGER. BIGGER BUTTS WILL UNDOUBTEDLY LEAD TO MORE EFFICIENT POOP CYCLING. EXCELLENT WORK ALL AROUND.

**Comment by zeke** [comment]
SEVENTEEN MONTHS OF WATCHING THIS REPO HAS FINALLY PAID OFF

**Pull request merged**
